<?php

namespace Container1j9ewIw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQ0BXrjService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NQ0BXrj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NQ0BXrj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'oTemplatesRegister' => ['privates', 'Combodo\\iTop\\Portal\\Service\\TemplatesProvider\\TemplatesRegister', 'getTemplatesRegisterService', true],
        ], [
            'oTemplatesRegister' => 'Combodo\\iTop\\Portal\\Service\\TemplatesProvider\\TemplatesRegister',
        ]);
    }
}
