<?php

namespace Container1j9ewIw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ValueResolverInterface.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Combodo\\iTop\\Portal\\Controller\\AggregatePageBrickController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\BrowseBrickController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\CreateBrickController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\DefaultController::HomeAction' => ['privates', '.service_locator.BlxiBKt', 'get_ServiceLocator_BlxiBKtService', true],
            'Combodo\\iTop\\Portal\\Controller\\DefaultController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\ManageBrickController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\ObjectController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\SessionMessageController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\UserProfileBrickController::RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Combodo\\iTop\\Portal\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Combodo\\iTop\\Portal\\Controller\\AggregatePageBrickController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\BrowseBrickController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\CreateBrickController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\DefaultController:HomeAction' => ['privates', '.service_locator.BlxiBKt', 'get_ServiceLocator_BlxiBKtService', true],
            'Combodo\\iTop\\Portal\\Controller\\DefaultController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\ManageBrickController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\ObjectController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\SessionMessageController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'Combodo\\iTop\\Portal\\Controller\\UserProfileBrickController:RegisterTemplates' => ['privates', '.service_locator.NQ0BXrj', 'get_ServiceLocator_NQ0BXrjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'Combodo\\iTop\\Portal\\Controller\\AggregatePageBrickController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\BrowseBrickController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\CreateBrickController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\DefaultController::HomeAction' => '?',
            'Combodo\\iTop\\Portal\\Controller\\DefaultController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\ManageBrickController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\ObjectController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\SessionMessageController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\UserProfileBrickController::RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Kernel::loadRoutes' => '?',
            'Combodo\\iTop\\Portal\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'Combodo\\iTop\\Portal\\Controller\\AggregatePageBrickController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\BrowseBrickController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\CreateBrickController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\DefaultController:HomeAction' => '?',
            'Combodo\\iTop\\Portal\\Controller\\DefaultController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\ManageBrickController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\ObjectController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\SessionMessageController:RegisterTemplates' => '?',
            'Combodo\\iTop\\Portal\\Controller\\UserProfileBrickController:RegisterTemplates' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
