<?php

namespace Container1j9ewIw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManageBrickControllerService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the public 'Combodo\iTop\Portal\Controller\ManageBrickController' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Controller\ManageBrickController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TemplatesProvider'.\DIRECTORY_SEPARATOR.'TemplatesProviderInterface.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BrickController.php';
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ManageBrickController.php';

        $a = ($container->services['url_generator'] ?? self::getUrlGeneratorService($container));

        $container->services['Combodo\\iTop\\Portal\\Controller\\ManageBrickController'] = $instance = new \Combodo\iTop\Portal\Controller\ManageBrickController(($container->services['brick_collection'] ?? $container->load('getBrickCollectionService')), ($container->services['scope_validator'] ?? $container->load('getScopeValidatorService')), $a, ($container->services['request_manipulator'] ?? $container->load('getRequestManipulatorService')), ($container->services['security_helper'] ?? $container->load('getSecurityHelperService')), ($container->services['brick_controller_helper'] ?? $container->load('getBrickControllerHelperService')));

        $instance->setRouter($a);
        $instance->SetTemplatesService(($container->privates['Combodo\\iTop\\Portal\\Service\\TemplatesProvider\\TemplatesProviderService'] ?? $container->load('getTemplatesProviderServiceService')));
        $instance->setContainer(($container->privates['.service_locator.XtuOrZY'] ?? $container->load('get_ServiceLocator_XtuOrZYService'))->withContext('Combodo\\iTop\\Portal\\Controller\\ManageBrickController', $container));

        return $instance;
    }
}
