<?php

namespace Container1j9ewIw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplatesProviderServiceService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the private 'Combodo\iTop\Portal\Service\TemplatesProvider\TemplatesProviderService' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Service\TemplatesProvider\TemplatesProviderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TemplatesProvider'.\DIRECTORY_SEPARATOR.'TemplatesProviderService.php';

        return $container->privates['Combodo\\iTop\\Portal\\Service\\TemplatesProvider\\TemplatesProviderService'] = new \Combodo\iTop\Portal\Service\TemplatesProvider\TemplatesProviderService($container->parameters['combodo.portal.instance.conf'], ($container->privates['templates_cache_pool'] ?? $container->load('getTemplatesCachePoolService')));
    }
}
