<?php

namespace Container1j9ewIw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplatesRegisterService extends Combodo_iTop_Portal_KernelProdContainer
{
    /*
     * Gets the private 'Combodo\iTop\Portal\Service\TemplatesProvider\TemplatesRegister' shared autowired service.
     *
     * @return \Combodo\iTop\Portal\Service\TemplatesProvider\TemplatesRegister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).''.\DIRECTORY_SEPARATOR.'env-production'.\DIRECTORY_SEPARATOR.'itop-portal-base'.\DIRECTORY_SEPARATOR.'portal'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TemplatesProvider'.\DIRECTORY_SEPARATOR.'TemplatesRegister.php';

        return $container->privates['Combodo\\iTop\\Portal\\Service\\TemplatesProvider\\TemplatesRegister'] = new \Combodo\iTop\Portal\Service\TemplatesProvider\TemplatesRegister();
    }
}
