<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1j9ewIw\Combodo_iTop_Portal_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1j9ewIw/Combodo_iTop_Portal_KernelProdContainer.php') {
    touch(__DIR__.'/Container1j9ewIw.legacy');

    return;
}

if (!\class_exists(Combodo_iTop_Portal_KernelProdContainer::class, false)) {
    \class_alias(\Container1j9ewIw\Combodo_iTop_Portal_KernelProdContainer::class, Combodo_iTop_Portal_KernelProdContainer::class, false);
}

return new \Container1j9ewIw\Combodo_iTop_Portal_KernelProdContainer([
    'container.build_hash' => '1j9ewIw',
    'container.build_id' => '986b9312',
    'container.build_time' => 1775792455,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1j9ewIw');
