<?php
//
// File generated by ... on the 2026-04-08T06:26:27+0200
// Please do not edit manually
//

/**
 * Classes and menus for combodo-oauth2-client (version 1.0.3)
 *
 * @author      iTop compiler
 * @license     http://opensource.org/licenses/AGPL-3.0
 */



abstract class Oauth2Client extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'provider'),
			'db_table' => 'priv_oauth2_client',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',
			'uniqueness_rules' => array (
  'no_duplicate' => 
  array (
    'attributes' => 
    array (
      0 => 'name',
      1 => 'provider',
    ),
    'filter' => NULL,
    'disabled' => NULL,
    'is_blocking' => NULL,
  ),
),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("name", array("sql"=>'name', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("description", array("sql"=>'description', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("provider", array("sql"=>'provider', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("client_id", array("sql"=>'client_id', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEncryptedPassword("client_secret", array("sql"=>'client_secret', "is_null_allowed"=>false, "on_target_delete"=>null, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEncryptedPassword("refresh_token", array("sql"=>'refresh_token', "is_null_allowed"=>true, "on_target_delete"=>null, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("refresh_token_expiration", array("sql"=>'refresh_token_expiration', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeEncryptedPassword("access_token", array("sql"=>'access_token', "is_null_allowed"=>true, "on_target_delete"=>null, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("access_token_expiration", array("sql"=>'access_token_expiration', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeString("scope", array("sql"=>'scope', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("authorization_state", array("sql"=>'authorization_state', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));
		MetaModel::Init_AddAttribute(new AttributeString("token_type", array("sql"=>'token_type', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false, "tracking_level"=>ATTRIBUTE_TRACKING_NONE)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col2' => 
  array (
    'fieldset:OAuth2Client:idp_info' => 
    array (
      0 => 'client_id',
      1 => 'client_secret',
      2 => 'scope',
      3 => 'access_token',
      4 => 'access_token_expiration',
      5 => 'refresh_token',
      6 => 'refresh_token_expiration',
      7 => 'token_type',
      8 => 'authorization_state',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:OAuth2Client:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'provider',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'provider',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'name',
  1 => 'provider',
));
;
	}

	protected function RegisterEventListeners()
	{
		parent::RegisterEventListeners();

		// listenerId = EVENT_DB_BEFORE_WRITE
		$this->RegisterCRUDListener("EVENT_DB_BEFORE_WRITE", 'EvtBeforeWriteOauthClient2', 0, 'combodo-oauth2-client');
		// listenerId = EVENT_DB_SET_ATTRIBUTES_FLAGS
		$this->RegisterCRUDListener("EVENT_DB_SET_ATTRIBUTES_FLAGS", 'EvtSetAttributeFlagsOauthClient2', 0, 'combodo-oauth2-client');
		// listenerId = EVENT_DB_SET_INITIAL_ATTRIBUTES_FLAGS
		$this->RegisterCRUDListener("EVENT_DB_SET_INITIAL_ATTRIBUTES_FLAGS", 'EvtSetInitialAttributeFlagsOauthClient2', 0, 'combodo-oauth2-client');
	}



        public function GetHybridauthProvider() : string
        {
          return Combodo\iTop\Oauth2Client\Model\Oauth2ClientService::GetHybridauthProvider($this);
        }




	public function PrefillCreationForm(&$aContextParam)
	{
		$this->Set('provider', $this->GetHybridauthProvider());

		parent::PrefillCreationForm($aContextParam);
	}


	/**
            * Event Listener for EVENT_DB_BEFORE_WRITE
            * An object is about to be written into the database.
            * The object can be modified.
            *
            * @param Combodo\iTop\Service\Events\EventData $oEventData Event data object
            */
          
	public function EvtBeforeWriteOauthClient2(Combodo\iTop\Service\Events\EventData $oEventData)
          {
            if ($oEventData->Get('is_new')) {
							$this->Set('provider', $this->GetHybridauthProvider());
            }
          }

	/**
            *
            * @param Combodo\iTop\Service\Events\EventData $oEventData Event data object
            */
          

	        public function EvtSetAttributeFlagsOauthClient2(Combodo\iTop\Service\Events\EventData $oEventData)
          {
                $this->AddAttributeFlags('access_token', OPT_ATT_HIDDEN);
                $this->AddAttributeFlags('authorization_state', OPT_ATT_HIDDEN);
                $this->AddAttributeFlags('refresh_token', OPT_ATT_HIDDEN);

                $this->AddAttributeFlags('access_token_expiration', OPT_ATT_READONLY);
                $this->AddAttributeFlags('refresh_token_expiration', OPT_ATT_READONLY);
                $this->AddAttributeFlags('token_type', OPT_ATT_READONLY);
                $this->AddAttributeFlags('provider', OPT_ATT_READONLY);
          }

	/**
            *
            * @param Combodo\iTop\Service\Events\EventData $oEventData Event data object
            */
          

	        public function EvtSetInitialAttributeFlagsOauthClient2(Combodo\iTop\Service\Events\EventData $oEventData)
          {
                $this->AddInitialAttributeFlags('access_token', OPT_ATT_HIDDEN);
                $this->AddInitialAttributeFlags('authorization_state', OPT_ATT_HIDDEN);
                $this->AddInitialAttributeFlags('refresh_token', OPT_ATT_HIDDEN);

                $this->AddInitialAttributeFlags('access_token_expiration', OPT_ATT_HIDDEN);
                $this->AddInitialAttributeFlags('refresh_token_expiration', OPT_ATT_HIDDEN);
                $this->AddInitialAttributeFlags('scope', OPT_ATT_HIDDEN);
                $this->AddInitialAttributeFlags('token_type', OPT_ATT_HIDDEN);
                $this->AddInitialAttributeFlags('provider', OPT_ATT_READONLY);

          }




        /**
        * Provide the acces_token fields mapping between hybridauth and iTop model
        * @return array
        */
        public function GetTokenModelToHybridauthMapping() : array {
          return [
            'access_token' => 'access_token',
            'token_type' => 'token_type',
            'refresh_token' => 'refresh_token',
            'expires_at' => 'access_token_expiration',
          ];
        }
        




        /**
        * Provide the mapping between hybridauth and iTop model
        * @return array
        */
        public function GetModelToHybridauthMapping() : array {
          return [];
        }
        



  public function DisplayBareHeader(WebPage $oPage, $bEditMode = false)
  {
		$aHeaderBlocks = parent::DisplayBareHeader($oPage, $bEditMode);

    if ($this instanceof Oauth2Client) {
      $aOauthConnectButtons = Combodo\iTop\Oauth2Client\Controller\Oauth2ClientController::GetButtons($this, $oPage);

      // Add the buttons in the existing toolbar
      reset($aHeaderBlocks['toolbar']);
      $sToolbarContainerKey = key($aHeaderBlocks['toolbar']);
      foreach ($aHeaderBlocks['toolbar'][$sToolbarContainerKey]->GetSubBlocks() as $sSubBlockId => $oSubBlock) {
        if (!($oSubBlock instanceof Combodo\iTop\Application\UI\Base\Component\Toolbar\Toolbar)) {
          continue;
        }
        // Look for the actions menu toolbar by checking if its ID starts with the good prefix
        if (stripos($sSubBlockId, MenuBlock::ACTIONS_TOOLBAR_ID_PREFIX) === 0) {
          foreach($aOauthConnectButtons as $oOauthConnectButton) {
            $oSubBlock->PrependSubBlock($oOauthConnectButton);
          }
          break;
        }
      }
		}

		return $aHeaderBlocks;

   }
        

}


class GitHubOauth2Client extends Oauth2Client
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'provider'),
			'db_table' => 'priv_oauth2_client_github',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



;
	}


}


class MicrosoftGraphOauth2Client extends Oauth2Client
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'tenant', 'provider'),
			'db_table' => 'priv_oauth2_client_microsoftgraph',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("tenant", array("sql"=>'tenant', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col2' => 
  array (
    'fieldset:OAuth2Client:idp_info' => 
    array (
      0 => 'tenant',
      1 => 'client_id',
      2 => 'client_secret',
      3 => 'scope',
      4 => 'access_token',
      5 => 'access_token_expiration',
      6 => 'refresh_token',
      7 => 'refresh_token_expiration',
      8 => 'token_type',
      9 => 'authorization_state',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:OAuth2Client:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'provider',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'tenant',
  2 => 'provider',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'name',
  1 => 'tenant',
  2 => 'provider',
));
;
	}

	protected function RegisterEventListeners()
	{
		parent::RegisterEventListeners();

		// listenerId = EVENT_DB_BEFORE_WRITE
		$this->RegisterCRUDListener("EVENT_DB_BEFORE_WRITE", 'EvtBeforeWriteMSGraph', 1, 'combodo-oauth2-client');
	}

	/**
            * Event Listener for EVENT_DB_BEFORE_WRITE
            * An object is about to be written into the database.
            * The object can be modified.
            *
            * @param Combodo\iTop\Service\Events\EventData $oEventData Event data object
            */
          
	public function EvtBeforeWriteMSGraph(Combodo\iTop\Service\Events\EventData $oEventData)
          {
            $sScope = $this->Get('scope');

            if (\utils::IsNullOrEmptyString($sScope)){
              //default value from hybridauth lib will be enforced (it contains offline_access already).
              return;
            }

            if (strpos($sScope, 'offline_access') ===false){
              $this->Set('scope', $sScope . ' offline_access');
            }
          }




        /**
        * Provide the mapping between hybridauth and iTop model
        * @return array
        */
        public function GetModelToHybridauthMapping() : array {
          return ['tenant' => 'tenant' ];
        }
        

}


class GoogleOauth2Client extends Oauth2Client
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'provider'),
			'db_table' => 'priv_oauth2_client_google',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



;
	}


}


class HeadlessOauth2Client extends Oauth2Client
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'provider'),
			'db_table' => 'priv_oauth2_client_headless_itop',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("username", array("sql"=>'username', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEncryptedPassword("password", array("sql"=>'password', "is_null_allowed"=>false, "on_target_delete"=>null, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("base_url", array("sql"=>'base_url', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("version", array("sql"=>'version', "is_null_allowed"=>true, "default_value"=>'1.3', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col2' => 
  array (
    'fieldset:OAuth2Client:idp_info' => 
    array (
      0 => 'base_url',
      1 => 'username',
      2 => 'password',
      3 => 'client_id',
      4 => 'client_secret',
      5 => 'scope',
      6 => 'access_token',
      7 => 'access_token_expiration',
      8 => 'refresh_token',
      9 => 'refresh_token_expiration',
      10 => 'token_type',
      11 => 'authorization_state',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:OAuth2Client:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'provider',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'provider',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'name',
  1 => 'provider',
));
;
	}





        /**
        * Provide the mapping between hybridauth and iTop model
        * @return array
        */
        public function GetModelToHybridauthMapping() : array {
          return [
            'username' => 'username',
            'password' => 'password',
            'version' => 'version',
            'url' => 'base_url',
          ];
        }
        

}


class KeycloakOauth2Client extends Oauth2Client
{
	public static function Init()
	{
		$aParams = array(			'category' => 'bizmodel,searchable',
			'key_type' => 'autoincrement',
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name', 'url', 'realm', 'provider'),
			'db_table' => 'priv_oauth2_client_keycloak',
			'db_key_field' => 'id',
			'db_finalclass_field' => 'finalclass',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("url", array("sql"=>'url', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("realm", array("sql"=>'realm', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col2' => 
  array (
    'fieldset:OAuth2Client:idp_info' => 
    array (
      0 => 'url',
      1 => 'realm',
      2 => 'client_id',
      3 => 'client_secret',
      4 => 'scope',
      5 => 'access_token',
      6 => 'access_token_expiration',
      7 => 'refresh_token',
      8 => 'refresh_token_expiration',
      9 => 'token_type',
      10 => 'authorization_state',
    ),
  ),
  'col:col1' => 
  array (
    'fieldset:OAuth2Client:baseinfo' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'provider',
    ),
  ),
));
		MetaModel::Init_SetZListItems('standard_search', array (
  0 => 'name',
  1 => 'url',
  2 => 'realm',
  3 => 'provider',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'name',
  1 => 'url',
  2 => 'realm',
  3 => 'provider',
));
;
	}





        /**
        * Provide the mapping between hybridauth and iTop model
        * @return array
        */
        public function GetModelToHybridauthMapping() : array {
          return ['realm' => 'realm', 'url' => 'url' ];
        }
        

}
//
// Menus
//
class MenuCreation_combodo_oauth2_client extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['ConfigurationTools'] = new MenuGroup('ConfigurationTools', 90, 'fas fa-cog' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['Integrations'] = new TemplateMenuNode('Integrations', '', $__comp_menus__['ConfigurationTools']->GetIndex(), 50 , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['Oauth2Client'] = new OQLMenuNode('Oauth2Client', "SELECT Oauth2Client", $__comp_menus__['Integrations']->GetIndex(), 100, true , 'Oauth2Client', UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
	}
} // class MenuCreation_combodo_oauth2_client
