<?php
/**
 * This file was automatically generated by the compiler on 2026-04-08 06:26:25 -- DO NOT EDIT
 */

define('COMPILATION_TIMESTAMP', '1775622385.9725');
/**
 * Data model from the delta file
 */



class lnkActionNotificationToContact extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => 'core/cmdb,application',
			'key_type' => 'autoincrement',
			'name_attcode' => array('action_id', 'contact_id'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('action_id', 'contact_id', 'trigger_id'),
			'db_table' => 'priv_lnk_action_notif_to_contact',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'uniqueness_rules' => array (
  '' => 
  array (
    'attributes' => 
    array (
      0 => 'action_id',
      1 => 'contact_id',
      2 => 'trigger_id',
    ),
    'filter' => NULL,
    'disabled' => false,
    'is_blocking' => true,
  ),
),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeExternalKey("action_id", array("targetclass"=>'ActionNotification', "allowed_values"=>null, "sql"=>'action_id', "is_null_allowed"=>false, "on_target_delete"=>null, "display_style"=>'select', "create_temporary_object"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id", array("targetclass"=>'Contact', "allowed_values"=>null, "sql"=>'contact_id', "is_null_allowed"=>false, "on_target_delete"=>null, "display_style"=>'select', "create_temporary_object"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("trigger_id", array("targetclass"=>'Trigger', "allowed_values"=>null, "sql"=>'trigger_id', "is_null_allowed"=>false, "on_target_delete"=>null, "display_style"=>'select', "create_temporary_object"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeBoolean("subscribed", array("sql"=>'subscribed', "is_null_allowed"=>false, "default_value"=>'true', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col1' => 
  array (
    'fieldset:lnkActionNotificationToContact:content' => 
    array (
      0 => 'action_id',
      1 => 'contact_id',
      2 => 'title',
    ),
  ),
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'action_id',
  1 => 'contact_id',
  2 => 'title',
));
;
	}


}


class ActionNewsroom extends ActionNotification
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile,core/cmdb,application',
			'key_type' => 'autoincrement',
			'complementary_name_attcode' => array('finalclass', 'description'),
			'name_attcode' => array('name'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('name'),
			'db_table' => 'priv_action_newsroom',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'style' =>  new ormStyle(null, null, null, null, null, 'core/../../images/icons/icons8-notification.svg'),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("title", array("sql"=>'title', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeText("message", array("sql"=>'message', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeImage("icon", array("is_null_allowed"=>true, "display_max_width"=>96, "display_max_height"=>96, "storage_max_width"=>256, "storage_max_height"=>256, "default_image"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("priority", array("allowed_values"=>new ValueSetEnum("1,2,3,4" ), "display_style"=>'list', "sql"=>'priority', "default_value"=>'4', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("test_recipient_id", array("targetclass"=>'Person', "allowed_values"=>null, "sql"=>'test_recipient_id', "is_null_allowed"=>true, "on_target_delete"=>DEL_MANUAL, "display_style"=>'select', "create_temporary_object"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeOQL("recipients", array("sql"=>'recipients', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeString("url", array("sql"=>'url', "is_null_allowed"=>false, "default_value"=>'$this->url()$', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  'col:col1' => 
  array (
    'fieldset:ActionNewsroom:content' => 
    array (
      0 => 'name',
      1 => 'description',
      2 => 'status',
      3 => 'language',
      4 => 'title',
      5 => 'message',
    ),
    'fieldset:ActionNewsroom:trigger' => 
    array (
      0 => 'trigger_list',
      1 => 'asynchronous',
    ),
  ),
  'col:col2' => 
  array (
    'fieldset:ActionNewsroom:settings' => 
    array (
      0 => 'priority',
      1 => 'icon',
      2 => 'test_recipient_id',
      3 => 'recipients',
      4 => 'url',
    ),
  ),
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'title',
  1 => 'description',
  2 => 'status',
  3 => 'language',
));
;
	}


		/**
            *
            *  Create EventNotificationNewsroom for each recipient
            * @param $oTrigger
            * @param $aContextArgs
            *
            * @return void
            * @throws \ArchivedObjectException
            * @throws \CoreCannotSaveObjectException
            * @throws \CoreException
            * @throws \CoreUnexpectedValue
            * @throws \CoreWarning
            * @throws \MySQLException
            * @throws \OQLException
            */

	public function DoExecute($oTrigger, $aContextArgs)
	{
		$aRecipientsIds = [];
		$oPotentialRecipientsSearch = DBObjectSearch::FromOQL($this->Get('recipients'));
		$oPotentialRecipientsSearch->AllowAllData();
		$oPotentialRecipientsSet = new DBObjectSet($oPotentialRecipientsSearch, array(), $aContextArgs);

		$bIsAsync = $this->IsAsynchronous();
		[$sPreviousLanguage, $aPreviousPluginProperties] = $this->SetNotificationLanguage();

		$sMessage = MetaModel::ApplyParams($this->Get('message'), $aContextArgs);
		$sTitle = MetaModel::ApplyParams($this->Get('title'), $aContextArgs);
		$sUrl = MetaModel::ApplyParams($this->Get('url'), $aContextArgs);
    $iObjectId = 0;
    $sObjectClass = null;
		if (array_key_exists('this->object()', $aContextArgs)) {
				$iObjectId = $aContextArgs['this->object()']->GetKey();
				$sObjectClass = get_class($aContextArgs['this->object()']);
    }

    if ($this->IsBeingTested()) {
      // If action is being tested, send notification to the test recipient only, no matter what (unsubscribed, disabled, no access to the backoffice, ...)
      $iTestRecipientId = $this->Get('test_recipient_id');
      if ($iTestRecipientId > 0) {
        $aRecipientsIds[] = $iTestRecipientId;
      }
    } else {
      // Otherwise, find the recipients to which we can actually send the notification among all the potential ones
      while ($oPotentialRecipient = $oPotentialRecipientsSet->Fetch()) {
        // Skip recipients that have no users
        if ($oPotentialRecipient instanceof Person && UserRights::GetUserFromPerson($oPotentialRecipient, false) === null) {
          continue;
        }

        // Skip potential recipient that have no user with access to the backoffice
        $oPotentialRecipientUsersSearch = DBObjectSearch::FromOQL("SELECT User WHERE contactid = " . $oPotentialRecipient->GetKey() . " AND status = 'enabled'");
        $oPotentialRecipientUsersSearch->AllowAllData();
        $oPotentialRecipientUsersSet = new DBObjectSet($oPotentialRecipientUsersSearch);
        $oPortalDispatcher = new PortalDispatcher('backoffice');
        // - Check if the user has access to the backoffice
        $bHasAccessToBackoffice = false;
        while ($oPotentialRecipientUser = $oPotentialRecipientUsersSet->Fetch()) {
          // Skip potential recipients with user that don't have access to the backoffice
          if (false === $oPortalDispatcher->IsUserAllowed($oPotentialRecipientUser)) {
                    continue;
          }

          $bHasAccessToBackoffice = true;
          break;
        }
        // - Skip it if necessary
        if (false === $bHasAccessToBackoffice) {
          continue;
        }

        // Skip potential recipients that have unsubscribed
        if (!\Combodo\iTop\Service\Notification\NotificationsService::GetInstance()->IsSubscribed($oTrigger, $this, $oPotentialRecipient)) {
          continue;
        }

        $aRecipientsIds[] = $oPotentialRecipient->GetKey();

        // Register subscription even though the notification is not sent yet
        \Combodo\iTop\Service\Notification\NotificationsService::GetInstance()->RegisterSubscription($oTrigger, $this, $oPotentialRecipient);
      }
    }

		if ($bIsAsync === true) {
		    AsyncSendNewsroom::AddToQueue($this->GetKey(), $oTrigger->GetKey(), $aRecipientsIds, $sMessage, $sTitle, $sUrl, $iObjectId, $sObjectClass);
    } else {
      foreach ($aRecipientsIds as $iRecipientId) {
        $oEvent = Combodo\iTop\Service\Notification\Event\EventNotificationNewsroomService::MakeEventFromAction($this, $iRecipientId, $oTrigger->GetKey(), $sMessage, $sTitle, $sUrl, $iObjectId, $sObjectClass);
          $oEvent->DBInsertNoReload();
      }
    }

		$this->SetNotificationLanguage($sPreviousLanguage, $aPreviousPluginProperties['language_code'] ?? null);
	}




	public static function GetAsynchronousGlobalSetting(): bool
	{
		return utils::GetConfig()->Get('notifications.itop.send_asynchronously');
	}


}


class EventNotificationNewsroom extends EventNotification
{
	public static function Init()
	{
		$aParams = array(			'category' => 'core/cmdb,view_in_gui',
			'key_type' => 'autoincrement',
			'name_attcode' => array('title'),
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array('title'),
			'db_table' => 'priv_event_newsroom',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',
			'order_by_default' => array('date' => false),);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("title", array("sql"=>'title', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeImage("icon", array("is_null_allowed"=>true, "display_max_width"=>128, "display_max_height"=>128, "storage_max_width"=>256, "storage_max_height"=>256, "default_image"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("priority", array("allowed_values"=>new ValueSetEnum("1,2,3,4" ), "display_style"=>'list', "sql"=>'priority', "default_value"=>'4', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeURL("url", array("target"=>'_blank', "sql"=>'url', "default_value"=>'', "is_null_allowed"=>false, "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeEnum("read", array("allowed_values"=>new ValueSetEnum("no,yes" ), "display_style"=>'list', "sql"=>'read', "default_value"=>'no', "is_null_allowed"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("read_date", array("sql"=>'read_date', "is_null_allowed"=>true, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("contact_id", array("targetclass"=>'Contact', "allowed_values"=>null, "sql"=>'contact_id', "is_null_allowed"=>false, "on_target_delete"=>null, "display_style"=>'select', "create_temporary_object"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));



		MetaModel::Init_SetZListItems('details', array (
  0 => 'date',
  1 => 'title',
  2 => 'message',
  3 => 'contact_id',
  4 => 'trigger_id',
  5 => 'action_id',
  6 => 'read',
  7 => 'url',
));
		MetaModel::Init_SetZListItems('summary', array (
  0 => 'date',
  1 => 'message',
));
		MetaModel::Init_SetZListItems('default_search', array (
  0 => 'action_id',
  1 => 'trigger_id',
  2 => 'date',
  3 => 'contact_id',
));
		MetaModel::Init_SetZListItems('list', array (
  0 => 'date',
  1 => 'contact_id',
  2 => 'message',
  3 => 'read',
  4 => 'read_date',
));
;
	}


}/**
 * Data model from the delta file
 */
const EVENT_DB_BEFORE_WRITE = 'EVENT_DB_BEFORE_WRITE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_BEFORE_WRITE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object is about to be written into the database.
The object can be modified.',
    'DBObject::OnInsert',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object inserted',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'is_new',
            'Creation flag',
            'boolean',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'stimulus_applied',
            'Life cycle stimulus applied (null if not within a transition)',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_CHECK_TO_WRITE = 'EVENT_DB_CHECK_TO_WRITE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_CHECK_TO_WRITE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'Check an object before it is written into the database (no change possible).
Call $this->AddCheckIssue($sErrorMessage) to report a blocking issue.
Call $this->AddCheckWarning($sWarningMessage) to display a warning.
      ',
    'cmdbAbstractObject::DoCheckToWrite',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object to check',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'is_new',
            'Creation flag',
            'boolean',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'stimulus_applied',
            'Life cycle stimulus applied (null if not within a transition)',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_AFTER_WRITE = 'EVENT_DB_AFTER_WRITE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_AFTER_WRITE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object has been written into the database.
The modifications can be propagated to other objects.',
    'DBObject::AfterInsert',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object inserted',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'is_new',
            'Creation flag',
            'boolean',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'changes',
            'For updates, the list of changes done during this operation',
            'array',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'stimulus_applied',
            'Life cycle stimulus applied (null if not within a transition)',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_CHECK_TO_DELETE = 'EVENT_DB_CHECK_TO_DELETE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_CHECK_TO_DELETE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'Check an object before it is deleted from the database.
Call $this->AddDeleteIssue($sIssueMessage) to signal an issue.',
    'cmdbAbstractObject::DoCheckToDelete',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object to check',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_ABOUT_TO_DELETE = 'EVENT_DB_ABOUT_TO_DELETE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_ABOUT_TO_DELETE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object is about to be deleted from the database',
    'cmdbAbstractObject::OnDelete',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object about to be deleted',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_AFTER_DELETE = 'EVENT_DB_AFTER_DELETE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_AFTER_DELETE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object has been deleted into the database',
    'DBObject::AfterDelete',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object deleted',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_ENUM_TRANSITIONS = 'EVENT_ENUM_TRANSITIONS';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_ENUM_TRANSITIONS',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'Manage the allowed transitions in current object state.
The only action allowed is to deny transitions with $this->DenyTransition($sTransitionCode)',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object where the stimulus is targeted',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'allowed_stimuli',
            'The list of available stimuli in the current state',
            'array',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_LINKS_CHANGED = 'EVENT_DB_LINKS_CHANGED';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_LINKS_CHANGED',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'At least one link class was changed',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object where the link is or was pointing to',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_OBJECT_RELOAD = 'EVENT_DB_OBJECT_RELOAD';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_OBJECT_RELOAD',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object has been re-loaded from the database',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object re-loaded',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_COMPUTE_VALUES = 'EVENT_DB_COMPUTE_VALUES';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_COMPUTE_VALUES',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object needs to be recomputed after changes',
    'DBObject::ComputeValues',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object inserted',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'is_new',
            'Creation flag',
            'boolean',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'stimulus_applied',
            'Life cycle stimulus applied (null if not within a transition)',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_ARCHIVE = 'EVENT_DB_ARCHIVE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_ARCHIVE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object has been archived',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object archived',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_UNARCHIVE = 'EVENT_DB_UNARCHIVE';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_UNARCHIVE',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'An object has been unarchived',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object unarchived',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_SET_ATTRIBUTES_FLAGS = 'EVENT_DB_SET_ATTRIBUTES_FLAGS';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_SET_ATTRIBUTES_FLAGS',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'Set object attributes flags.
Call $this->AddAttributeFlags($sAttCode, $iFlags) for all the attributes to be set for this target state.',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The current object',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'target_state',
            'The target state in which to evaluate the flags',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DB_SET_INITIAL_ATTRIBUTES_FLAGS = 'EVENT_DB_SET_INITIAL_ATTRIBUTES_FLAGS';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DB_SET_INITIAL_ATTRIBUTES_FLAGS',
    [
        'cmdbAbstractObject' => 'cmdbAbstractObject',
    ],
    'Set object initial attributes flags.
Call $this->AddInitialAttributeFlags($sAttCode, $iFlags) for all the initial attributes to be set initially.',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The current object',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_DOWNLOAD_DOCUMENT = 'EVENT_DOWNLOAD_DOCUMENT';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_DOWNLOAD_DOCUMENT',
    [
        'Document' => 'Document',
    ],
    'A document has been downloaded from the GUI',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'object',
            'The object containing the document',
            'DBObject',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'att_code',
            'The optional object attribute code hosting the document',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'document',
            'The document downloaded',
            'ormDocument',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'content_disposition',
            'The content disposition of the document ("inline" or "attachment")',
            'string',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'debug_info',
            'Debug string',
            'string',
        ),
    ],
    'application'
  )
);

const EVENT_LOGIN = 'EVENT_LOGIN';
\Combodo\iTop\Service\Events\EventService::RegisterEvent(
  new \Combodo\iTop\Service\Events\Description\EventDescription(
    'EVENT_LOGIN',
    [
    ],
    'Inform the listeners about the connection states',
    '',
    [
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'code',
            'The login step result code (LoginWebPage::EXIT_CODE_...) ',
            'integer',
        ),
        new \Combodo\iTop\Service\Events\Description\EventDataDescription(
            'state',
            'Current login state (LoginWebPage::LOGIN_STATE_CONNECTED...)',
            'string',
        ),
    ],
    'application'
  )
);



/* Resource access control abstraction. Can be herited by abstract resource access control classes. Generaly controlled using UR_ACTION_MODIFY access right. */
abstract class AbstractResource extends cmdbAbstractObject
{
	public static function Init()
	{
		$aParams = array(			'category' => '',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => '',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



;
	}


}

/* AdminTools menu access control. */
abstract class ResourceAdminMenu extends AbstractResource
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => '',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



;
	}


}

/* RunQueriesMenu menu access control. */
abstract class ResourceRunQueriesMenu extends AbstractResource
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => '',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



;
	}


}

/* System menu access control. */
abstract class ResourceSystemMenu extends AbstractResource
{
	public static function Init()
	{
		$aParams = array(			'category' => 'grant_by_profile',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => '',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();



;
	}


}

/** Acknowledge welcome popup messages */
class WelcomePopupAcknowledge extends DBObject
{
	public static function Init()
	{
		$aParams = array(			'category' => '',
			'key_type' => 'autoincrement',
			'name_attcode' => '',
			'image_attcode' => '',
			'state_attcode' => '',
			'reconc_keys' => array(),
			'db_table' => 'priv_welcome_popup_acknowledge',
			'db_key_field' => 'id',
			'db_finalclass_field' => '',);
		MetaModel::Init_Params($aParams);
		MetaModel::Init_InheritAttributes();
		MetaModel::Init_AddAttribute(new AttributeString("message_uuid", array("sql"=>'message_uuid', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeExternalKey("user_id", array("targetclass"=>'User', "allowed_values"=>null, "sql"=>'user_id', "is_null_allowed"=>false, "on_target_delete"=>DEL_SILENT, "display_style"=>'select', "create_temporary_object"=>false, "depends_on"=>array(), "always_load_in_tables"=>false)));
		MetaModel::Init_AddAttribute(new AttributeDateTime("acknowledge_date", array("sql"=>'acknowledge_date', "is_null_allowed"=>false, "default_value"=>'', "allowed_values"=>null, "depends_on"=>array(), "always_load_in_tables"=>false)));



;
	}


}
//
// Menus
//
class MenuCreation_application extends ModuleHandlerAPI
{
	public static function OnMenuCreation()
	{
		global $__comp_menus__; // ensure that the global variable is indeed global !
		$__comp_menus__['WelcomeMenu'] = new MenuGroup('WelcomeMenu', 10, 'fas fa-home' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['MyShortcuts'] = new ShortcutContainerMenuNode('MyShortcuts', $__comp_menus__['WelcomeMenu']->GetIndex(), 20 , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['AdminTools'] = new MenuGroup('AdminTools', 80, 'fas fa-tools' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['UserManagement'] = new TemplateMenuNode('UserManagement', '', $__comp_menus__['AdminTools']->GetIndex(), 10 , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['UserAccountsMenu'] = new OQLMenuNode('UserAccountsMenu', "SELECT User", $__comp_menus__['UserManagement']->GetIndex(), 11, true , 'User', UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
		$__comp_menus__['ProfilesMenu'] = new OQLMenuNode('ProfilesMenu', "SELECT URP_Profiles", $__comp_menus__['UserManagement']->GetIndex(), 12, true , 'URP_Profiles', UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
		$__comp_menus__['Queries'] = new TemplateMenuNode('Queries', '', $__comp_menus__['AdminTools']->GetIndex(), 30 , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['RunQueriesMenu'] = new WebPageMenuNode('RunQueriesMenu', utils::GetAbsoluteUrlAppRoot()."pages/run_query.php", $__comp_menus__['Queries']->GetIndex(), 31 , 'ResourceRunQueriesMenu', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['QueryMenu'] = new OQLMenuNode('QueryMenu', "SELECT Query", $__comp_menus__['Queries']->GetIndex(), 32, true , 'Query', UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
		$__comp_menus__['ExportMenu'] = new WebPageMenuNode('ExportMenu', utils::GetAbsoluteUrlAppRoot()."webservices/export-v2.php?interactive=1", $__comp_menus__['Queries']->GetIndex(), 33 , 'ResourceAdminMenu', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['DataModelMenu'] = new WebPageMenuNode('DataModelMenu', utils::GetAbsoluteUrlAppRoot()."pages/schema.php", $__comp_menus__['AdminTools']->GetIndex(), 40 , 'ResourceRunQueriesMenu', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['UniversalSearchMenu'] = new WebPageMenuNode('UniversalSearchMenu', utils::GetAbsoluteUrlAppRoot()."pages/UniversalSearch.php", $__comp_menus__['Queries']->GetIndex(), 35 , 'ResourceAdminMenu', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['ConfigurationTools'] = new MenuGroup('ConfigurationTools', 90, 'fas fa-cog' , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['Integrations'] = new TemplateMenuNode('Integrations', '', $__comp_menus__['ConfigurationTools']->GetIndex(), 50 , null, UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
		$__comp_menus__['DataSources'] = new OQLMenuNode('DataSources', "SELECT SynchroDataSource", $__comp_menus__['ConfigurationTools']->GetIndex(), 20, true , 'SynchroDataSource', UR_ACTION_MODIFY, UR_ALLOWED_YES, null, true);
		$__comp_menus__['NotificationsMenu'] = new WebPageMenuNode('NotificationsMenu', utils::GetAbsoluteUrlAppRoot()."pages/notifications.php", $__comp_menus__['ConfigurationTools']->GetIndex(), 40 , 'Trigger', UR_ACTION_MODIFY, UR_ALLOWED_YES, null);
	}
} // class MenuCreation_application
/**
 * Custom zlists 
 */

/**
 * Portal(s) definition(s) extracted from the XML definition at compile time
 */
class PortalDispatcherData
{
	protected static $aData = array (
  'itop-portal' => 
  array (
    'rank' => 1.0,
    'handler' => 'PortalDispatcher',
    'url' => 'pages/exec.php?exec_module=itop-portal-base&exec_page=index.php&portal_id=itop-portal',
    'allow' => 
    array (
    ),
    'deny' => 
    array (
    ),
  ),
  'backoffice' => 
  array (
    'rank' => 2.0,
    'handler' => 'PortalDispatcher',
    'url' => 'pages/UI.php',
    'allow' => 
    array (
    ),
    'deny' => 
    array (
      0 => 'Portal user',
    ),
  ),
);

	public static function GetData($sPortalId = null)
	{
		if ($sPortalId === null) return self::$aData;
		if (!array_key_exists($sPortalId, self::$aData)) return array();
		return self::$aData[$sPortalId];
	}
}

/**
 * Modules parameters extracted from the XML definition at compile time
 */
class ModulesXMLParameters
{
	protected static $aData = array (
  'authent-local' => 
  array (
    'password_validation.pattern' => '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\da-zA-Z]).{8,}$',
    'password_validation.message' => 
    array (
    ),
  ),
  'itop-portal' => 
  array (
    'lazy_loading_threshold' => '500',
  ),
  'itop-hub-connector' => 
  array (
    'url' => 'https://www.itophub.io',
    'route_landing' => '/my-instances/landing-from-remote',
    'route_landing_stateless' => '/stateless-remote-itop/landing-from-remote-stateless',
    'route_fetch_unread_messages' => '/api/messages',
    'route_mark_all_messages_as_read' => '/api/messages/mark-all-as-read',
    'route_view_all_messages' => '/messages',
    'setup_url' => '../pages/exec.php?exec_module=itop-hub-connector&exec_page=launch.php&target=inform_after_setup',
    'rgpd_url' => 'https://www.itophub.io/page/data-privacy',
  ),
  'itop-tickets' => 
  array (
    'relation_context' => 
    array (
      'UserRequest' => 
      array (
        'impacts' => 
        array (
          'down' => 
          array (
            'items' => 
            array (
              0 => 
              array (
                'oql' => '
										SELECT FCI, I
										FROM FunctionalCI AS FCI
												 JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
												 JOIN Incident AS I ON L.ticket_id = I.id
										WHERE (I.status NOT IN (\'closed\', \'resolved\'))
										  AND (L.impact_code != \'not_impacted\')
										  AND (I.id != :this->id)
										',
                'dict' => 'Tickets:Related:OpenIncidents',
                'icon' => 'itop-incident-mgmt-itil/images/incident-red.png',
                'default' => 'yes',
              ),
              1 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\', \'rejected\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.id != :this->id)
                    ',
                'dict' => 'Tickets:Related:OpenChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-ongoing.png',
              ),
              2 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.id != :this->id)
                      AND (C.end_date < NOW() AND C.end_date > DATE_SUB(NOW(), INTERVAL 3 DAY ))
                    ',
                'dict' => 'Tickets:Related:RecentChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-done.png',
              ),
            ),
          ),
        ),
      ),
      'Incident' => 
      array (
        'impacts' => 
        array (
          'down' => 
          array (
            'items' => 
            array (
              0 => 
              array (
                'oql' => '
										SELECT FCI, I
										FROM FunctionalCI AS FCI
												 JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
												 JOIN Incident AS I ON L.ticket_id = I.id
										WHERE (I.status NOT IN (\'closed\', \'resolved\'))
										  AND (L.impact_code != \'not_impacted\')
										  AND (I.id != :this->id)
										',
                'dict' => 'Tickets:Related:OpenIncidents',
                'icon' => 'itop-incident-mgmt-itil/images/incident-red.png',
                'default' => 'yes',
              ),
              1 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\', \'rejected\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.id != :this->id)
                    ',
                'dict' => 'Tickets:Related:OpenChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-ongoing.png',
              ),
              2 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.id != :this->id)
                      AND (C.end_date < NOW() AND C.end_date > DATE_SUB(NOW(), INTERVAL 3 DAY ))
                    ',
                'dict' => 'Tickets:Related:RecentChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-done.png',
              ),
            ),
          ),
        ),
      ),
      'Change' => 
      array (
        'impacts' => 
        array (
          'down' => 
          array (
            'items' => 
            array (
              0 => 
              array (
                'oql' => '
										SELECT FCI, I
										FROM FunctionalCI AS FCI
												 JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
												 JOIN Incident AS I ON L.ticket_id = I.id
										WHERE (I.status NOT IN (\'closed\', \'resolved\'))
										  AND (L.impact_code != \'not_impacted\')
										  AND (I.id != :this->id)
										',
                'dict' => 'Tickets:Related:OpenIncidents',
                'icon' => 'itop-incident-mgmt-itil/images/incident-red.png',
                'default' => 'yes',
              ),
              1 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\', \'rejected\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.id != :this->id)
                    ',
                'dict' => 'Tickets:Related:OpenChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-ongoing.png',
              ),
              2 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.id != :this->id)
                      AND (C.end_date < NOW() AND C.end_date > DATE_SUB(NOW(), INTERVAL 3 DAY ))
                    ',
                'dict' => 'Tickets:Related:RecentChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-done.png',
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  'itop-config-mgmt' => 
  array (
    'relation_context' => 
    array (
      'FunctionalCI' => 
      array (
        'impacts' => 
        array (
          'down' => 
          array (
            'items' => 
            array (
              0 => 
              array (
                'oql' => '
										SELECT FCI, I
										FROM FunctionalCI AS FCI
												 JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
												 JOIN Incident AS I ON L.ticket_id = I.id
										WHERE (I.status NOT IN (\'closed\', \'resolved\'))
										  AND (L.impact_code != \'not_impacted\')
										',
                'dict' => 'Tickets:Related:OpenIncidents',
                'icon' => 'itop-incident-mgmt-itil/images/incident-red.png',
                'default' => 'yes',
              ),
              1 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\', \'rejected\'))
                      AND (L.impact_code != \'not_impacted\')
                    ',
                'dict' => 'Tickets:Related:OpenChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-ongoing.png',
              ),
              2 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status IN (\'closed\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.end_date < NOW() AND C.end_date > DATE_SUB(NOW(), INTERVAL 3 DAY ))
                    ',
                'dict' => 'Tickets:Related:RecentChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-done.png',
              ),
            ),
          ),
          'up' => 
          array (
            'items' => 
            array (
              0 => 
              array (
                'oql' => '
										SELECT FCI, I
										FROM FunctionalCI AS FCI
												 JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
												 JOIN Incident AS I ON L.ticket_id = I.id
										WHERE (I.status NOT IN (\'closed\', \'resolved\'))
										  AND (L.impact_code != \'not_impacted\')
										',
                'dict' => 'Tickets:Related:OpenIncidents',
                'icon' => 'itop-incident-mgmt-itil/images/incident-red.png',
                'default' => 'yes',
              ),
              1 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status NOT IN (\'closed\', \'rejected\'))
                      AND (L.impact_code != \'not_impacted\')
                    ',
                'dict' => 'Tickets:Related:OpenChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-ongoing.png',
              ),
              2 => 
              array (
                'oql' => '
                    SELECT FCI, C
                    FROM FunctionalCI AS FCI
                           JOIN lnkFunctionalCIToTicket AS L ON L.functionalci_id = FCI.id
                           JOIN Change AS C ON L.ticket_id = C.id
                    WHERE (C.outage = \'yes\')
                      AND (C.status IN (\'closed\'))
                      AND (L.impact_code != \'not_impacted\')
                      AND (C.end_date < NOW() AND C.end_date > DATE_SUB(NOW(), INTERVAL 3 DAY ))
                    ',
                'dict' => 'Tickets:Related:RecentChanges',
                'icon' => 'itop-change-mgmt-itil/images/change-done.png',
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  'authent-token' => 
  array (
    'personal_tokens_allowed_profiles' => 
    array (
      0 => 'Administrator',
    ),
    'application_token' => 
    array (
      'allow_fallback_token' => 'false',
    ),
    'enable_myaccount_menu' => true,
  ),
  'combodo-webhook-integration' => 
  array (
    'prefer_asynchronous' => false,
    'timeout' => 5,
    'certificate_check' => true,
    'ca_certificate_file' => '',
  ),
);

	public static function GetData($sModuleId = null)
	{
		if ($sModuleId === null) return self::$aData;
		if (!array_key_exists($sModuleId, self::$aData)) return array();
		return self::$aData[$sModuleId];
	}
}

/**
 * Relations
 */
MetaModel::RegisterRelation('impacts');
